Running Move unit tests
[ PASS    ] 0x1::A::a
[ PASS    ] 0x1::A::b
[ PASS    ] 0x1::A::c
[ FAIL    ] 0x1::A::x
[ FAIL    ] 0x1::A::y
0x1::A::a
Output: Ok(ChangeSet { accounts: {} })
0x1::A::b
Output: Ok(ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("A"), name: Identifier("A"), type_params: [] }: New([0])} }} })
0x1::A::c
Output: Ok(ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("A"), name: Identifier("A"), type_params: [] }: New([0])} }} })
0x1::A::x
Output: Ok(ChangeSet { accounts: {} })
0x1::A::y
Output: Ok(ChangeSet { accounts: {00000000000000000000000000000001: AccountChangeSet { modules: {}, resources: {StructTag { address: 00000000000000000000000000000001, module: Identifier("A"), name: Identifier("A"), type_params: [] }: New([0])} }} })

Test failures:

Failures in 0x1::A:

┌── x ──────
│ error[E11001]: test failure
│   ┌─ storage_on_error_empty_and_non_empty.move:6:9
│   │
│ 5 │     fun x() {
│   │         - In this function in 0x1::A
│ 6 │         abort 0
│   │         ^^^^^^^ Test was not expected to error, but it aborted with code 0 originating in the module 00000000000000000000000000000001::A rooted here
│ 
│ 
│ ────── Storage state at point of failure ──────
│ <empty>
└──────────────────


┌── y ──────
│ error[E11001]: test failure
│    ┌─ storage_on_error_empty_and_non_empty.move:12:9
│    │
│ 10 │     fun y(a: signer) {
│    │         - In this function in 0x1::A
│ 11 │         move_to(&a, A {});
│ 12 │         abort 0
│    │         ^^^^^^^ Test was not expected to error, but it aborted with code 0 originating in the module 00000000000000000000000000000001::A rooted here
│ 
│ 
│ ────── Storage state at point of failure ──────
│ 0x1:
│ 	=> key 0x1::A::A {
│ 	    dummy_field: false
│ 	}
│ 
└──────────────────

Test result: FAILED. Total tests: 5; passed: 3; failed: 2
